defaults: &defaults
  puppet:
    master_domain: vhostman.cdu.edu.cn
    hieradata: <%= Rails.root %>/tmp/hieradata/
    hiera_templates: <%= Rails.root %>/config/puppet/hiera_templates

  sftp:
    chroot: /root/www

  servers:
    types:
      nginx_server: Nginx 服务器
      dns_server: Dns 服务器

  dns:
    types: [A, CNAME, MX]

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults